"""Add padron_alumnos table

Revision ID: 02c1c10b5c49
Revises: 98ab017e5a44
Create Date: 2026-02-22 00:11:02.457447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c1c10b5c49'
down_revision: Union[str, None] = '98ab017e5a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('padron_alumnos',
    sa.Column('id_matricula', sa.String(length=10), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_matricula')
    )
    op.create_index(op.f('ix_padron_alumnos_id_matricula'), 'padron_alumnos', ['id_matricula'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_padron_alumnos_id_matricula'), table_name='padron_alumnos')
    op.drop_table('padron_alumnos')
    # ### end Alembic commands ###
