"""Generic script.py.mako template for Alembic migrations."""
"""Add student profile fields

Revision ID: 10f28c2be4bb
Revises: 3530c23a023b
Create Date: 2026-03-30 23:40:27.091668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10f28c2be4bb'
down_revision: Union[str, None] = '3530c23a023b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('correo_alterno', sa.String(length=200), nullable=True))
    op.add_column('usuarios', sa.Column('celular', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('descripcion_personal', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'descripcion_personal')
    op.drop_column('usuarios', 'celular')
    op.drop_column('usuarios', 'correo_alterno')
    # ### end Alembic commands ###
