"""Generic script.py.mako template for Alembic migrations."""
"""Fix is_google_login schema drift

Revision ID: 3530c23a023b
Revises: 1b7b14f97a2d
Create Date: 2026-03-26 19:53:49.377121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3530c23a023b'
down_revision: Union[str, None] = '1b7b14f97a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_google_login', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_column('usuarios', 'auth_provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('auth_provider', sa.VARCHAR(length=50), server_default=sa.text("'local'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('usuarios', 'is_google_login')
    # ### end Alembic commands ###
