"""Generic script.py.mako template for Alembic migrations."""
"""initial_schema

Revision ID: 4eb27c45a724
Revises: 
Create Date: 2026-02-18 12:47:32.164518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb27c45a724'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id_evento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('periodo', sa.String(length=20), nullable=False, comment='INVIERNO | FEB_JUN | VERANO | AGO_DIC'),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_table('usuarios',
    sa.Column('id_matricula', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('correo', sa.String(length=200), nullable=False),
    sa.Column('carrera', sa.String(length=100), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_matricula'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('usuario_eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_matricula', sa.String(length=20), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id_evento'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_matricula'], ['usuarios.id_matricula'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_eventos')
    op.drop_table('usuarios')
    op.drop_table('eventos')
    # ### end Alembic commands ###
