from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ab017e5a44'
down_revision: Union[str, None] = '4eb27c45a724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_auditoria',
    sa.Column('id_log', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False, comment='LOGIN_EXITOSO | LOGIN_FALLIDO | REGISTRO_NUEVO | LOGOUT | TOKEN_INVALIDO | ...'),
    sa.Column('id_matricula', sa.String(length=20), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('id_matricula', sa.String(length=20), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_matricula'], ['usuarios.id_matricula'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_table('logs_auditoria')
    # ### end Alembic commands ###
