"""Generic script.py.mako template for Alembic migrations."""
"""add_google_auth_provider

Revision ID: de8fdd8c3c98
Revises: e1f2a3b4c5d6
Create Date: 2026-03-26 18:33:51.323062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de8fdd8c3c98'
down_revision: Union[str, None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_espera_alumno_evento'), table_name='lista_espera')
    op.drop_index(op.f('idx_espera_proyecto_tiempo'), table_name='lista_espera')
    op.drop_table('lista_espera')
    op.drop_index(op.f('ix_pre_auth_tokens_token_hash'), table_name='pre_auth_tokens')
    op.drop_table('pre_auth_tokens')
    op.drop_column('empresas', 'descripcion')
    op.drop_column('empresas', 'id_asociado')
    op.drop_column('empresas', 'razon_social')
    op.drop_column('proyectos', 'capacidad_espera_max')
    op.add_column('usuarios', sa.Column('auth_provider', sa.String(length=50), server_default='local', nullable=False))
    op.drop_index(op.f('uq_usuarios_empresa_por_empresa'), table_name='usuarios', postgresql_where="(((rol)::text = 'empresa'::text) AND (id_empresa IS NOT NULL))")
    op.drop_column('usuarios', 'is_google_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_google_login', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('uq_usuarios_empresa_por_empresa'), 'usuarios', ['id_empresa'], unique=True, postgresql_where="(((rol)::text = 'empresa'::text) AND (id_empresa IS NOT NULL))")
    op.drop_column('usuarios', 'auth_provider')
    op.add_column('proyectos', sa.Column('capacidad_espera_max', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('empresas', sa.Column('razon_social', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('id_asociado', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Clave de convenio, ej. SF-XXX24'))
    op.add_column('empresas', sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('pre_auth_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('id_matricula', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('expira_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('usado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_matricula'], ['usuarios.id_matricula'], name=op.f('pre_auth_tokens_id_matricula_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pre_auth_tokens_pkey')),
    sa.UniqueConstraint('token_hash', name=op.f('pre_auth_tokens_token_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_pre_auth_tokens_token_hash'), 'pre_auth_tokens', ['token_hash'], unique=True)
    op.create_table('lista_espera',
    sa.Column('id_espera', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_matricula', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id_proyecto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_evento', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp_registro', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id_evento'], name=op.f('lista_espera_id_evento_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_matricula'], ['usuarios.id_matricula'], name=op.f('lista_espera_id_matricula_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id_proyecto'], name=op.f('lista_espera_id_proyecto_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_espera', name=op.f('lista_espera_pkey')),
    sa.UniqueConstraint('id_matricula', 'id_proyecto', name=op.f('uq_espera_alumno_proyecto'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_espera_proyecto_tiempo'), 'lista_espera', ['id_proyecto', 'timestamp_registro'], unique=False)
    op.create_index(op.f('idx_espera_alumno_evento'), 'lista_espera', ['id_matricula', 'id_evento'], unique=False)
    # ### end Alembic commands ###
