"""Generic script.py.mako template for Alembic migrations."""
"""add_rol_to_usuarios

Revision ID: fb70194972ff
Revises: a1b2c3d4e5f6
Create Date: 2026-03-09 15:32:12.649494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fb70194972ff'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_inscripciones_alumno_evento'), table_name='inscripciones')
    op.drop_index(op.f('idx_inscripciones_proyecto'), table_name='inscripciones')
    op.drop_index(op.f('idx_proyectos_evento'), table_name='proyectos')
    op.add_column('usuarios', sa.Column('rol', sa.String(length=20), server_default='alumno', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'rol')
    op.create_index(op.f('idx_proyectos_evento'), 'proyectos', ['id_evento'], unique=False)
    op.create_index(op.f('idx_inscripciones_proyecto'), 'inscripciones', ['id_proyecto'], unique=False)
    op.create_index(op.f('idx_inscripciones_alumno_evento'), 'inscripciones', ['id_matricula', 'id_evento'], unique=False)
    # ### end Alembic commands ###
