"""Generic script.py.mako template for Alembic migrations."""
"""add_rol_to_usuarios

Revision ID: fb70194972ff
Revises: a1b2c3d4e5f6
Create Date: 2026-03-09 15:32:12.649494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb70194972ff'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_espera_alumno_evento'), table_name='lista_espera')
    op.drop_index(op.f('idx_espera_proyecto_tiempo'), table_name='lista_espera')
    op.drop_table('lista_espera')
    op.drop_index(op.f('idx_inscripciones_alumno_evento'), table_name='inscripciones')
    op.drop_index(op.f('idx_inscripciones_proyecto'), table_name='inscripciones')
    op.drop_index(op.f('idx_proyectos_evento'), table_name='proyectos')
    op.add_column('usuarios', sa.Column('rol', sa.String(length=20), server_default='alumno', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'rol')
    op.create_index(op.f('idx_proyectos_evento'), 'proyectos', ['id_evento'], unique=False)
    op.create_index(op.f('idx_inscripciones_proyecto'), 'inscripciones', ['id_proyecto'], unique=False)
    op.create_index(op.f('idx_inscripciones_alumno_evento'), 'inscripciones', ['id_matricula', 'id_evento'], unique=False)
    op.create_table('lista_espera',
    sa.Column('id_espera', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_matricula', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id_proyecto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_evento', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp_registro', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id_evento'], name=op.f('lista_espera_id_evento_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_matricula'], ['usuarios.id_matricula'], name=op.f('lista_espera_id_matricula_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id_proyecto'], name=op.f('lista_espera_id_proyecto_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_espera', name=op.f('lista_espera_pkey')),
    sa.UniqueConstraint('id_matricula', 'id_proyecto', name=op.f('uq_espera_alumno_proyecto'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_espera_proyecto_tiempo'), 'lista_espera', ['id_proyecto', 'timestamp_registro'], unique=False)
    op.create_index(op.f('idx_espera_alumno_evento'), 'lista_espera', ['id_matricula', 'id_evento'], unique=False)
    # ### end Alembic commands ###
